### ISSUE TITLE
Floatthead too slow on Firefox

### ISSUE THREAD

**Issue by ercanozkaya** [timble/kodekit-ui#11]
See: joomlatools/joomlatools-framework#58

**Comment by robinpoort** [comment]
Fixed in https://github.com/joomlatools/joomlatools-framework/issues/58

**Comment by robinpoort** [comment]
No longer working in Chrom since thead won't accept position sticky. Change to th and test on browsers

**Comment by robinpoort** [comment]
Fixed: https://github.com/timble/kodekit-ui/commit/910525012c9fd24328c611767e47cda01fafa6d2
