### ISSUE TITLE
Namespace datepicker against conflicts

### ISSUE THREAD

**Issue by ercanozkaya** [timble/kodekit-ui#13]
See: https://support.joomlatools.com/forums/topic/7034-document-category-tree-shows-loading-after-upgrade-to-docman-3-0-2#comment-38050

If the datepicker is loaded again we lose our custom options, so we should namespace it just like we do with tooltip, modal, etc.

**Comment by amazeika** [comment]
@ercan we need to make this fix available to the customer ASAP. The template developers decline any responsability so we've stepped up to provide the customer with a solution. Can you please handle it?

**Comment by johanjanssens** [comment]
@ercanozkaya @amazeika As requested on chat, would it be possible to replace this with a html5 date field instead and not require any additional JS code? This would require the least amount of maintenance on our end.

**Comment by ercanozkaya** [comment]
@johanjanssens html5 date field still requires a polyfill. Only Chrome on desktop supports it.
We can solve it by namespacing the datepicker, let's do that since we already use the technique for tooltips etc.

**Comment by ercanozkaya** [comment]
Namespaced it and pushed a fix to the client. @robinpoort can you still check the site please? Styling for the datepicker is a bit off. Is that something we can fix?

**Comment by robinpoort** [comment]
@ercanozkaya Not sure what you mean here

![datepicker](https://cloud.githubusercontent.com/assets/4848082/24453532/927210a6-1488-11e7-9478-212ee28815c5.png)

Looks quite alright to me. I checked on master, should I checkout another branch?
