### ISSUE TITLE
Undefined function in main.js

### ISSUE THREAD

**Issue by ercanozkaya** [timble/kodekit-ui#30]
See: https://github.com/timble/kodekit-ui/blob/4738d1edf21ad083fbcbff1871fba7f221e9a9f3/src/js/main.js#L497-L497

We run `tabsCalculateScroll` in all resize events. However the function is only defined if `$tabsScroller` has a length above.

**Comment by ercanozkaya** [comment]
@robinpoort I can replicate this by opening the console in Docman documents view

**Comment by robinpoort** [comment]
Fixed in v0.2.1
